OPENAI_API_KEY: "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"
GEMINI_API_KEY: "AIzaSyCEbGoSoYeD1ZX4mUWD2yUPDax-UNdDl44"
