import pandas as pd
from faker import Faker
import random

fake = Faker()

# Define job titles and their relevant skills
job_titles = [
    "Software Engineer", "Data Scientist", "Product Manager", 
    "Graphic Designer", "Marketing Specialist", "Sales Manager",
    "DevOps Engineer", "Business Analyst", "HR Manager",
    "Financial Analyst", "Content Writer", "UX Designer",
    "Network Administrator", "Cybersecurity Specialist", "Database Administrator",
    "Mobile Developer", "Cloud Architect", "IT Support Specialist",
    "Project Manager", "Quality Assurance Engineer", "SEO Specialist",
    "Social Media Manager", "Customer Service Representative", "Operations Manager",
    "Mechanical Engineer", "Electrical Engineer", "Civil Engineer",
    "Architect", "Interior Designer", "Biomedical Engineer",
    "Marketing Manager", "Marketing Director", "Marketing Research Analyst",
    "Marketing Communications Manager", "Marketing Consultant", "Public Relations",
    "Social Media Assistant", "Brand Manager", "SEO Manager",
    "Content Marketing Manager", "Copywriter", "Media Buyer",
    "Digital Marketing Manager", "eCommerce Marketing Specialist", "Brand Strategist",
    "Vice President of Marketing", "Media Relations Coordinator", "Administrative Assistant",
    "Receptionist", "Office Manager", "Auditing Clerk",
    "Bookkeeper", "Account Executive", "Branch Manager",
    "Business Manager", "Quality Control Coordinator", "Administrative Manager",
    "Chief Executive Officer", "Risk Manager", "Human Resources",
    "Computer Scientist", "IT Professional", "UX Designer & UI Developer",
    "SQL Developer", "Web Designer", "Web Developer",
    "Help Desk Worker/Desktop Support", "Data Entry", "DevOps Engineer",
    "Computer Programmer", "Information Security Analyst", "Artificial Intelligence Engineer",
    "IT Manager", "Technical Specialist", "Application Developer",
    "Chief Technology Officer (CTO)", "Chief Information Officer (CIO)", "Sales Associate",
    "Sales Representative", "Retail Worker", "Store Manager",
    "Real Estate Broker", "Account Manager", "Area Sales Manager",
    "Direct Salesperson", "Director of Inside Sales", "Outside Sales Manager",
    "Sales Analyst", "Market Development Manager", "B2B Sales Specialist",
    "Sales Engineer", "Merchandising Associate", "Construction Worker",
    "Taper", "Plumber", "Heavy Equipment Operator",
    "Vehicle or Equipment Cleaner", "Carpenter", "Electrician",
    "Painter", "Welder", "Handyman",
    "Boilermaker", "Crane Operator", "Building Inspector",
    "Pipefitter", "Sheet Metal Worker", "Iron Worker",
    "Mason", "Roofer", "Solar Photovoltaic Installer",
    "Well Driller", "Office Assistant", "Secretary",
    "Office Clerk", "File Clerk", "Account Collector",
    "Administrative Specialist", "Executive Assistant", "Program Administrator",
    "Program Manager", "Administrative Analyst",
    "Board of Directors", "C-Level or C-Suite", "Shareholders", "Managers", "Supervisors", 
    "Front-Line Employees", "Quality Control", "Human Resources", "Accounting Staff", 
    "Marketing Staff", "Purchasing Staff", "Shipping and Receiving Staff", "Virtual Assistant", 
    "Customer Service", "Customer Support", "Concierge", "Help Desk", "Customer Service Manager", 
    "Technical Support Specialist", "Account Representative", "Client Service Specialist", 
    "Customer Care Associate", "Operations Assistant", "Operations Coordinator", "Operations Analyst", 
    "Operations Director", "Vice President of Operations", "Operations Professional", "Scrum Master", 
    "Continuous Improvement Lead", "Continuous Improvement Consultant", "Credit Authorizer", 
    "Benefits Manager", "Credit Counselor", "Accountant", "Accounting Analyst", "Accounting Director", 
    "Accounts Payable/Receivable Clerk", "Auditor", "Budget Analyst", "Controller", "Finance Manager", 
    "Economist", "Payroll Manager", "Payroll Clerk", "Financial Planner", "Financial Services Representative", 
    "Finance Director", "Commercial Loan Officer", "Engineer", "Assistant Engineer", "Chemical Engineer", 
    "Chief Engineer", "Drafter", "Engineering Technician", "Geological Engineer", "Biological Engineer", 
    "Maintenance Engineer", "Mining Engineer", "Nuclear Engineer", "Petroleum Engineer", "Plant Engineer", 
    "Production Engineer", "Quality Engineer", "Safety Engineer", "Researcher", "Research Assistant", 
    "Data Analyst", "Biostatistician", "Title Researcher", "Market Researcher", "Title Analyst", 
    "Medical Researcher", "Mentor", "Tutor/Online Tutor", "Teacher", "Teaching Assistant", 
    "Substitute Teacher", "Preschool Teacher", "Test Scorer", "Online ESL Instructor", "Professor", 
    "Assistant Professor", "Artist", "Video Editor", "Video or Film Producer", "Playwright", "Musician", 
    "Novelist/Writer", "Computer Animator", "Photographer", "Camera Operator", "Sound Engineer", 
    "Motion Picture Director", "Actor", "Music Producer", "Director of Photography", "Housekeeper", 
    "Flight Attendant", "Travel Agent", "Hotel Front Door Greeter", "Bellhop", "Cruise Director", 
    "Entertainment Specialist", "Hotel Manager", "Front Desk Associate", "Front Desk Manager", 
    "Group Sales", "Event Planner", "Porter", "Spa Manager", "Wedding Coordinator", "Cruise Ship Attendant", 
    "Casino Host", "Hotel Receptionist", "Reservationist", "Events Manager", "Meeting Planner", 
    "Lodging Manager", "Director of Maintenance", "Valet",
    "Doctor", "Game Developer", "Marketing Executive", "Customer Service Executive", "Digital Marketing Executive",
    "Content Writer", "Sales Executive", "Lawyer", "Merchant Navy", "Chartered Accountant", "Quality Assurance Tester",
    "AI Engineer", "Machine Learning Engineer", "Blockchain Developer", "Full Stack Software Developer", "Management Consultant",
    "Engineering Manager", "IT Systems Manager", "Data Engineer", "Software Architect", "Investment Banker", "Surgeon"
]

skills_dict = {
    "Software Engineer": ["Python", "Java", "C++", "Git", "SQL"],
    "Data Scientist": ["Python", "R", "SQL", "Machine Learning", "Statistics"],
    "Product Manager": ["Product Management", "Agile", "Scrum", "Market Research", "Leadership"],
    "Graphic Designer": ["Adobe Photoshop", "Illustrator", "InDesign", "Creativity", "Typography"],
    "Marketing Specialist": ["SEO", "Content Marketing", "Social Media", "Google Analytics", "Copywriting"],
    "Sales Manager": ["Sales", "CRM", "Negotiation", "Customer Service", "Leadership"],
    "DevOps Engineer": ["AWS", "Docker", "Kubernetes", "CI/CD", "Linux"],
    "Business Analyst": ["Business Analysis", "SQL", "Data Analysis", "Project Management", "Communication"],
    "HR Manager": ["Recruitment", "Employee Relations", "HR Policies", "Performance Management", "Leadership"],
    "Financial Analyst": ["Financial Analysis", "Excel", "Accounting", "Financial Modeling", "Data Analysis"],
    "Content Writer": ["Content Writing", "SEO", "Copywriting", "Editing", "Research"],
    "UX Designer": ["User Research", "Wireframing", "Prototyping", "Adobe XD", "Usability Testing"],
    "Network Administrator": ["Networking", "Cisco", "Firewall", "VPN", "Troubleshooting"],
    "Cybersecurity Specialist": ["Cybersecurity", "Penetration Testing", "Network Security", "Incident Response", "SIEM"],
    "Database Administrator": ["SQL", "Database Management", "Backup and Recovery", "Performance Tuning", "Oracle"],
    "Mobile Developer": ["iOS", "Android", "Swift", "Kotlin", "React Native"],
    "Cloud Architect": ["AWS", "Azure", "Cloud Computing", "Infrastructure", "DevOps"],
    "IT Support Specialist": ["Technical Support", "Troubleshooting", "Windows", "Linux", "Customer Service"],
    "Project Manager": ["Project Management", "Agile", "Scrum", "Budgeting", "Risk Management"],
    "Quality Assurance Engineer": ["QA Testing", "Automation", "Selenium", "JIRA", "Test Planning"],
    "SEO Specialist": ["SEO", "Google Analytics", "Keyword Research", "Content Optimization", "Link Building"],
    "Social Media Manager": ["Social Media", "Content Creation", "Analytics", "Engagement", "Branding"],
    "Customer Service Representative": ["Customer Service", "Communication", "Problem Solving", "CRM", "Patience"],
    "Operations Manager": ["Operations Management", "Process Improvement", "Leadership", "Supply Chain", "Logistics"],
    "Mechanical Engineer": ["Mechanical Engineering", "CAD", "SolidWorks", "Manufacturing", "Thermodynamics"],
    "Electrical Engineer": ["Electrical Engineering", "Circuit Design", "MATLAB", "Power Systems", "Electronics"],
    "Civil Engineer": ["Civil Engineering", "AutoCAD", "Structural Analysis", "Construction Management", "Surveying"],
    "Architect": ["Architecture", "AutoCAD", "Revit", "Design", "Building Codes"],
    "Interior Designer": ["Interior Design", "AutoCAD", "SketchUp", "Space Planning", "Color Theory"],
    "Biomedical Engineer": ["Biomedical Engineering", "Medical Devices", "LabVIEW", "Biomaterials", "Regulatory Compliance"],
    "Marketing Manager": ["Marketing Strategy", "Campaign Management", "SEO", "Social Media", "Budgeting"],
    "Marketing Director": ["Leadership", "Strategic Planning", "Brand Management", "Digital Marketing", "Market Research"],
    "Marketing Research Analyst": ["Data Analysis", "Market Research", "SPSS", "Excel", "Survey Design"],
    "Marketing Communications Manager": ["Public Relations", "Content Creation", "Branding", "Social Media", "Communication"],
    "Marketing Consultant": ["Market Analysis", "Strategy Development", "SEO", "Social Media", "Client Management"],
    "Public Relations": ["Media Relations", "Communication", "Press Releases", "Event Planning", "Crisis Management"],
    "Social Media Assistant": ["Social Media", "Content Creation", "Analytics", "Engagement", "Branding"],
    "Brand Manager": ["Brand Strategy", "Marketing", "Market Research", "Product Development", "Communication"],
    "SEO Manager": ["SEO", "Google Analytics", "Keyword Research", "Content Optimization", "Link Building"],
    "Content Marketing Manager": ["Content Strategy", "SEO", "Copywriting", "Social Media", "Analytics"],
    "Copywriter": ["Copywriting", "SEO", "Content Creation", "Editing", "Creativity"],
    "Media Buyer": ["Media Planning", "Negotiation", "Analytics", "Budgeting", "Digital Marketing"],
    "Digital Marketing Manager": ["Digital Marketing", "SEO", "PPC", "Social Media", "Analytics"],
    "eCommerce Marketing Specialist": ["eCommerce", "SEO", "Digital Marketing", "Google Analytics", "Conversion Optimization"],
    "Brand Strategist": ["Brand Strategy", "Market Research", "Communication", "Creativity", "Marketing"],
    "Vice President of Marketing": ["Leadership", "Strategic Planning", "Brand Management", "Digital Marketing", "Market Research"],
    "Media Relations Coordinator": ["Media Relations", "Communication", "Press Releases", "Event Planning", "Public Relations"],
    "Administrative Assistant": ["Office Management", "Communication", "Scheduling", "Microsoft Office", "Data Entry"],
    "Receptionist": ["Communication", "Customer Service", "Scheduling", "Microsoft Office", "Multitasking"],
    "Office Manager": ["Office Management", "Administration", "Communication", "Scheduling", "Budgeting"],
    "Auditing Clerk": ["Auditing", "Accounting", "Data Entry", "Attention to Detail", "Excel"],
    "Bookkeeper": ["Accounting", "QuickBooks", "Data Entry", "Excel", "Financial Reporting"],
    "Account Executive": ["Sales", "Client Management", "Communication", "Negotiation", "CRM"],
    "Branch Manager": ["Leadership", "Sales", "Customer Service", "Operations Management", "Financial Management"],
    "Business Manager": ["Business Management", "Leadership", "Financial Management", "Operations", "Communication"],
    "Quality Control Coordinator": ["Quality Assurance", "Attention to Detail", "Data Analysis", "Communication", "Problem Solving"],
    "Administrative Manager": ["Office Management", "Administration", "Leadership", "Communication", "Budgeting"],
    "Chief Executive Officer": ["Leadership", "Strategic Planning", "Financial Management", "Communication", "Decision Making"],
    "Risk Manager": ["Risk Assessment", "Risk Management", "Compliance", "Data Analysis", "Communication"],
    "Human Resources": ["Recruitment", "Employee Relations", "HR Policies", "Performance Management", "Communication"],
    "Computer Scientist": ["Programming", "Algorithms", "Data Structures", "Machine Learning", "Research"],
    "IT Professional": ["Technical Support", "Networking", "Troubleshooting", "Windows", "Linux"],
    "UX Designer & UI Developer": ["User Research", "Wireframing", "Prototyping", "HTML/CSS", "JavaScript"],
    "SQL Developer": ["SQL", "Database Management", "Data Analysis", "Performance Tuning", "PL/SQL"],
    "Web Designer": ["HTML/CSS", "JavaScript", "Adobe Photoshop", "UX/UI Design", "Creativity"],
    "Web Developer": ["HTML/CSS", "JavaScript", "React", "Node.js", "PHP"],
    "Help Desk Worker/Desktop Support": ["Technical Support", "Troubleshooting", "Windows", "Customer Service", "Networking"],
    "Data Entry": ["Data Entry", "Attention to Detail", "Typing", "Microsoft Office", "Time Management"],
    "Computer Programmer": ["Programming", "Java", "C++", "Python", "Debugging"],
    "Information Security Analyst": ["Cybersecurity", "Penetration Testing", "Network Security", "Incident Response", "SIEM"],
    "Artificial Intelligence Engineer": ["Machine Learning", "Python", "TensorFlow", "Data Analysis", "Algorithms"],
    "IT Manager": ["IT Management", "Networking", "Security", "Project Management", "Leadership"],
    "Technical Specialist": ["Technical Support", "Troubleshooting", "Networking", "Windows", "Linux"],
    "Application Developer": ["Java", "C#", ".NET", "SQL", "Software Development"],
    "Chief Technology Officer (CTO)": ["Leadership", "Strategic Planning", "Software Development", "IT Management", "Innovation"],
    "Chief Information Officer (CIO)": ["Leadership", "IT Strategy", "Project Management", "Cybersecurity", "Budgeting"],
    "Sales Associate": ["Customer Service", "Sales", "Communication", "Product Knowledge", "Cash Handling"],
    "Sales Representative": ["Sales", "Communication", "Negotiation", "Customer Service", "CRM"],
    "Retail Worker": ["Customer Service", "Sales", "Cash Handling", "Product Knowledge", "Communication"],
    "Store Manager": ["Retail Management", "Sales", "Customer Service", "Inventory Management", "Leadership"],
    "Real Estate Broker": ["Real Estate", "Sales", "Negotiation", "Customer Service", "Market Analysis"],
    "Account Manager": ["Client Management", "Sales", "Communication", "Negotiation", "CRM"],
    "Area Sales Manager": ["Sales Management", "Leadership", "Customer Service", "CRM", "Market Analysis"],
    "Direct Salesperson": ["Sales", "Communication", "Customer Service", "Negotiation", "Product Knowledge"],
    "Director of Inside Sales": ["Sales Management", "Leadership", "CRM", "Customer Service", "Strategy"],
    "Outside Sales Manager": ["Sales Management", "Customer Service", "Negotiation", "CRM", "Market Analysis"],
    "Sales Analyst": ["Data Analysis", "Sales", "Excel", "Reporting", "Market Research"],
    "Market Development Manager": ["Market Research", "Sales", "Strategy", "Communication", "Leadership"],
    "B2B Sales Specialist": ["B2B Sales", "Communication", "Negotiation", "CRM", "Customer Service"],
    "Sales Engineer": ["Sales", "Engineering", "Technical Support", "Communication", "Product Knowledge"],
    "Merchandising Associate": ["Merchandising", "Inventory Management", "Sales", "Customer Service", "Product Knowledge"],
    "Construction Worker": ["Construction", "Safety", "Physical Stamina", "Teamwork", "Tools"],
    "Taper": ["Drywall", "Taping", "Finishing", "Construction", "Attention to Detail"],
    "Plumber": ["Plumbing", "Pipefitting", "Troubleshooting", "Customer Service", "Tools"],
    "Heavy Equipment Operator": ["Equipment Operation", "Safety", "Construction", "Maintenance", "Physical Stamina"],
    "Vehicle or Equipment Cleaner": ["Cleaning", "Attention to Detail", "Physical Stamina", "Safety", "Tools"],
    "Carpenter": ["Carpentry", "Construction", "Tools", "Attention to Detail", "Physical Stamina"],
    "Electrician": ["Electrical Work", "Wiring", "Troubleshooting", "Safety", "Tools"],
    "Painter": ["Painting", "Attention to Detail", "Safety", "Tools", "Physical Stamina"],
    "Welder": ["Welding", "Safety", "Attention to Detail", "Tools", "Physical Stamina"],
    "Handyman": ["Maintenance", "Repair", "Tools", "Customer Service", "Troubleshooting"],
    "Boilermaker": ["Boilermaking", "Welding", "Safety", "Tools", "Physical Stamina"],
    "Crane Operator": ["Crane Operation", "Safety", "Construction", "Maintenance", "Physical Stamina"],
    "Building Inspector": ["Inspection", "Construction", "Attention to Detail", "Safety", "Codes"],
    "Pipefitter": ["Pipefitting", "Welding", "Safety", "Tools", "Construction"],
    "Sheet Metal Worker": ["Sheet Metal", "Fabrication", "Welding", "Safety", "Tools"],
    "Iron Worker": ["Ironwork", "Welding", "Construction", "Safety", "Tools"],
    "Mason": ["Masonry", "Construction", "Tools", "Attention to Detail", "Physical Stamina"],
    "Roofer": ["Roofing", "Construction", "Safety", "Tools", "Physical Stamina"],
    "Solar Photovoltaic Installer": ["Solar Installation", "Electrical Work", "Safety", "Tools", "Construction"],
    "Well Driller": ["Drilling", "Safety", "Maintenance", "Tools", "Physical Stamina"],
    "Office Assistant": ["Office Management", "Communication", "Data Entry", "Microsoft Office", "Scheduling"],
    "Secretary": ["Communication", "Scheduling", "Office Management", "Microsoft Office", "Data Entry"],
    "Office Clerk": ["Data Entry", "Filing", "Office Management", "Communication", "Microsoft Office"],
    "File Clerk": ["Filing", "Data Entry", "Attention to Detail", "Office Management", "Communication"],
    "Account Collector": ["Debt Collection", "Communication", "Negotiation", "Customer Service", "Data Entry"],
    "Administrative Specialist": ["Office Management", "Communication", "Data Entry", "Microsoft Office", "Scheduling"],
    "Executive Assistant": ["Office Management", "Communication", "Scheduling", "Microsoft Office", "Multitasking"],
    "Program Administrator": ["Program Management", "Communication", "Budgeting", "Scheduling", "Data Analysis"],
    "Program Manager": ["Project Management", "Communication", "Budgeting", "Leadership", "Strategic Planning"],
    "Administrative Analyst": ["Data Analysis", "Communication", "Reporting", "Office Management", "Problem Solving"],
    "Board of Directors": ["Leadership", "Strategic Planning", "Governance", "Financial Oversight", "Decision Making"],
    "C-Level or C-Suite": ["Leadership", "Strategic Planning", "Financial Management", "Communication", "Decision Making"],
    "Shareholders": ["Investment Knowledge", "Financial Analysis", "Decision Making", "Communication", "Governance"],
    "Managers": ["Leadership", "Team Management", "Communication", "Project Management", "Problem Solving"],
    "Supervisors": ["Team Supervision", "Communication", "Problem Solving", "Time Management", "Leadership"],
    "Front-Line Employees": ["Customer Service", "Communication", "Teamwork", "Problem Solving", "Time Management"],
    "Quality Control": ["Quality Assurance", "Attention to Detail", "Data Analysis", "Problem Solving", "Communication"],
    "Human Resources": ["Recruitment", "Employee Relations", "HR Policies", "Performance Management", "Communication"],
    "Accounting Staff": ["Accounting", "Financial Reporting", "Excel", "Attention to Detail", "Data Entry"],
    "Marketing Staff": ["Marketing Strategy", "Content Creation", "SEO", "Social Media", "Analytics"],
    "Purchasing Staff": ["Procurement", "Negotiation", "Inventory Management", "Supply Chain", "Vendor Management"],
    "Shipping and Receiving Staff": ["Logistics", "Inventory Management", "Attention to Detail", "Forklift Operation", "Safety"],
    "Virtual Assistant": ["Remote Work", "Communication", "Scheduling", "Microsoft Office", "Data Entry"],
    "Customer Service": ["Customer Service", "Communication", "Problem Solving", "CRM", "Patience"],
    "Customer Support": ["Technical Support", "Communication", "Problem Solving", "Customer Service", "Troubleshooting"],
    "Concierge": ["Customer Service", "Communication", "Problem Solving", "Multitasking", "Local Knowledge"],
    "Help Desk": ["Technical Support", "Troubleshooting", "Communication", "Customer Service", "Networking"],
    "Customer Service Manager": ["Customer Service", "Leadership", "Communication", "Problem Solving", "CRM"],
    "Technical Support Specialist": ["Technical Support", "Troubleshooting", "Networking", "Windows", "Linux"],
    "Account Representative": ["Sales", "Client Management", "Communication", "Negotiation", "CRM"],
    "Client Service Specialist": ["Customer Service", "Communication", "Problem Solving", "Client Management", "CRM"],
    "Customer Care Associate": ["Customer Service", "Communication", "Problem Solving", "CRM", "Patience"],
    "Operations Assistant": ["Operations Management", "Communication", "Scheduling", "Microsoft Office", "Data Entry"],
    "Operations Coordinator": ["Operations Management", "Communication", "Scheduling", "Project Management", "Problem Solving"],
    "Operations Analyst": ["Data Analysis", "Operations Management", "Excel", "Problem Solving", "Communication"],
    "Operations Director": ["Operations Management", "Leadership", "Strategic Planning", "Communication", "Problem Solving"],
    "Vice President of Operations": ["Leadership", "Operations Management", "Strategic Planning", "Communication", "Problem Solving"],
    "Operations Professional": ["Operations Management", "Process Improvement", "Communication", "Leadership", "Problem Solving"],
    "Scrum Master": ["Scrum", "Agile", "Project Management", "Communication", "Leadership"],
    "Continuous Improvement Lead": ["Process Improvement", "Lean", "Six Sigma", "Project Management", "Communication"],
    "Continuous Improvement Consultant": ["Process Improvement", "Lean", "Six Sigma", "Project Management", "Communication"],
    "Credit Authorizer": ["Credit Analysis", "Financial Analysis", "Attention to Detail", "Communication", "Decision Making"],
    "Benefits Manager": ["Benefits Administration", "HR Policies", "Communication", "Compliance", "Employee Relations"],
    "Credit Counselor": ["Credit Counseling", "Financial Analysis", "Communication", "Problem Solving", "Customer Service"],
    "Accountant": ["Accounting", "Financial Reporting", "Excel", "Attention to Detail", "Data Entry"],
    "Accounting Analyst": ["Accounting", "Financial Analysis", "Excel", "Attention to Detail", "Data Entry"],
    "Accounting Director": ["Leadership", "Accounting", "Financial Reporting", "Strategic Planning", "Communication"],
    "Accounts Payable/Receivable Clerk": ["Accounts Payable", "Accounts Receivable", "Data Entry", "Attention to Detail", "Excel"],
    "Auditor": ["Auditing", "Accounting", "Attention to Detail", "Compliance", "Data Analysis"],
    "Budget Analyst": ["Budgeting", "Financial Analysis", "Excel", "Attention to Detail", "Data Analysis"],
    "Controller": ["Accounting", "Financial Reporting", "Leadership", "Strategic Planning", "Communication"],
    "Finance Manager": ["Financial Management", "Financial Analysis", "Leadership", "Strategic Planning", "Communication"],
    "Economist": ["Economic Analysis", "Data Analysis", "Research", "Statistical Analysis", "Communication"],
    "Payroll Manager": ["Payroll Management", "HR Policies", "Attention to Detail", "Compliance", "Communication"],
    "Payroll Clerk": ["Payroll Processing", "Data Entry", "Attention to Detail", "Excel", "Communication"],
    "Financial Planner": ["Financial Planning", "Investment Management", "Client Management", "Communication", "Financial Analysis"],
    "Financial Services Representative": ["Customer Service", "Financial Analysis", "Sales", "Communication", "Client Management"],
    "Finance Director": ["Leadership", "Financial Management", "Strategic Planning", "Communication", "Financial Analysis"],
    "Commercial Loan Officer": ["Loan Processing", "Financial Analysis", "Sales", "Communication", "Client Management"],
    "Engineer": ["Engineering", "Problem Solving", "Technical Skills", "Project Management", "Communication"],
    "Assistant Engineer": ["Engineering Support", "Technical Skills", "Problem Solving", "Data Analysis", "Communication"],
    "Chemical Engineer": ["Chemical Engineering", "Process Engineering", "Problem Solving", "Technical Skills", "Safety"],
    "Chief Engineer": ["Leadership", "Engineering Management", "Strategic Planning", "Technical Skills", "Communication"],
    "Drafter": ["Drafting", "AutoCAD", "Technical Drawing", "Attention to Detail", "Communication"],
    "Engineering Technician": ["Technical Support", "Engineering", "Problem Solving", "Data Analysis", "Communication"],
    "Geological Engineer": ["Geological Engineering", "Field Work", "Data Analysis", "Problem Solving", "Technical Skills"],
    "Biological Engineer": ["Biological Engineering", "Lab Work", "Research", "Data Analysis", "Technical Skills"],
    "Maintenance Engineer": ["Maintenance", "Engineering", "Problem Solving", "Technical Skills", "Safety"],
    "Mining Engineer": ["Mining Engineering", "Field Work", "Problem Solving", "Technical Skills", "Safety"],
    "Nuclear Engineer": ["Nuclear Engineering", "Safety", "Technical Skills", "Problem Solving", "Research"],
    "Petroleum Engineer": ["Petroleum Engineering", "Field Work", "Problem Solving", "Technical Skills", "Safety"],
    "Plant Engineer": ["Plant Engineering", "Maintenance", "Problem Solving", "Technical Skills", "Safety"],
    "Production Engineer": ["Production Engineering", "Process Improvement", "Problem Solving", "Technical Skills", "Safety"],
    "Quality Engineer": ["Quality Assurance", "Problem Solving", "Data Analysis", "Technical Skills", "Attention to Detail"],
    "Safety Engineer": ["Safety Engineering", "Risk Assessment", "Problem Solving", "Technical Skills", "Attention to Detail"],
    "Researcher": ["Research", "Data Analysis", "Problem Solving", "Technical Skills", "Communication"],
    "Research Assistant": ["Research Support", "Data Analysis", "Problem Solving", "Technical Skills", "Communication"],
    "Data Analyst": ["Data Analysis", "Excel", "SQL", "Problem Solving", "Communication"],
    "Biostatistician": ["Biostatistics", "Data Analysis", "Research", "Statistical Analysis", "Communication"],
    "Title Researcher": ["Title Research", "Data Analysis", "Attention to Detail", "Communication", "Problem Solving"],
    "Market Researcher": ["Market Research", "Data Analysis", "Survey Design", "Communication", "Problem Solving"],
    "Title Analyst": ["Title Analysis", "Data Analysis", "Attention to Detail", "Communication", "Problem Solving"],
    "Medical Researcher": ["Medical Research", "Data Analysis", "Lab Work", "Research", "Communication"],
    "Mentor": ["Mentoring", "Communication", "Leadership", "Problem Solving", "Coaching"],
    "Tutor/Online Tutor": ["Tutoring", "Communication", "Subject Knowledge", "Patience", "Problem Solving"],
    "Teacher": ["Teaching", "Communication", "Classroom Management", "Subject Knowledge", "Patience"],
    "Teaching Assistant": ["Classroom Support", "Communication", "Patience", "Problem Solving", "Subject Knowledge"],
    "Substitute Teacher": ["Classroom Management", "Communication", "Flexibility", "Subject Knowledge", "Patience"],
    "Preschool Teacher": ["Early Childhood Education", "Communication", "Patience", "Classroom Management", "Creativity"],
    "Test Scorer": ["Attention to Detail", "Data Entry", "Communication", "Problem Solving", "Subject Knowledge"],
    "Online ESL Instructor": ["ESL Teaching", "Communication", "Patience", "Flexibility", "Subject Knowledge"],
    "Professor": ["Teaching", "Research", "Communication", "Subject Knowledge", "Leadership"],
    "Assistant Professor": ["Teaching", "Research", "Communication", "Subject Knowledge", "Problem Solving"],
    "Artist": ["Creativity", "Artistic Skills", "Communication", "Attention to Detail", "Technical Skills"],
    "Video Editor": ["Video Editing", "Creativity", "Attention to Detail", "Technical Skills", "Communication"],
    "Video or Film Producer": ["Video Production", "Project Management", "Creativity", "Communication", "Technical Skills"],
    "Playwright": ["Writing", "Creativity", "Storytelling", "Communication", "Attention to Detail"],
    "Musician": ["Music Performance", "Creativity", "Technical Skills", "Communication", "Attention to Detail"],
    "Novelist/Writer": ["Writing", "Creativity", "Storytelling", "Communication", "Attention to Detail"],
    "Computer Animator": ["Animation", "Creativity", "Technical Skills", "Attention to Detail", "Communication"],
    "Photographer": ["Photography", "Creativity", "Technical Skills", "Attention to Detail", "Communication"],
    "Camera Operator": ["Camera Operation", "Technical Skills", "Attention to Detail", "Creativity", "Communication"],
    "Sound Engineer": ["Sound Engineering", "Technical Skills", "Attention to Detail", "Creativity", "Communication"],
    "Motion Picture Director": ["Directing", "Creativity", "Leadership", "Communication", "Technical Skills"],
    "Actor": ["Acting", "Creativity", "Communication", "Flexibility", "Attention to Detail"],
    "Music Producer": ["Music Production", "Creativity", "Technical Skills", "Communication", "Attention to Detail"],
    "Director of Photography": ["Cinematography", "Creativity", "Technical Skills", "Attention to Detail", "Communication"],
    "Housekeeper": ["Cleaning", "Attention to Detail", "Time Management", "Customer Service", "Communication"],
    "Flight Attendant": ["Customer Service", "Communication", "Safety", "Problem Solving", "Flexibility"],
    "Travel Agent": ["Travel Planning", "Customer Service", "Communication", "Sales", "Attention to Detail"],
    "Hotel Front Door Greeter": ["Customer Service", "Communication", "Hospitality", "Problem Solving", "Flexibility"],
    "Bellhop": ["Customer Service", "Communication", "Physical Stamina", "Problem Solving", "Flexibility"],
    "Cruise Director": ["Leadership", "Customer Service", "Communication", "Event Planning", "Problem Solving"],
    "Entertainment Specialist": ["Entertainment", "Creativity", "Customer Service", "Communication", "Problem Solving"],
    "Hotel Manager": ["Hotel Management", "Leadership", "Customer Service", "Communication", "Problem Solving"],
    "Front Desk Associate": ["Customer Service", "Communication", "Problem Solving", "Multitasking", "Attention to Detail"],
    "Front Desk Manager": ["Leadership", "Customer Service", "Communication", "Problem Solving", "Multitasking"],
    "Group Sales": ["Sales", "Customer Service", "Communication", "Negotiation", "Problem Solving"],
    "Event Planner": ["Event Planning", "Project Management", "Communication", "Creativity", "Problem Solving"],
    "Porter": ["Customer Service", "Communication", "Physical Stamina", "Problem Solving", "Flexibility"],
    "Spa Manager": ["Spa Management", "Customer Service", "Leadership", "Communication", "Problem Solving"],
    "Wedding Coordinator": ["Event Planning", "Customer Service", "Communication", "Creativity", "Problem Solving"],
    "Cruise Ship Attendant": ["Customer Service", "Communication", "Flexibility", "Problem Solving", "Physical Stamina"],
    "Casino Host": ["Customer Service", "Communication", "Sales", "Problem Solving", "Flexibility"],
    "Hotel Receptionist": ["Customer Service", "Communication", "Problem Solving", "Multitasking", "Attention to Detail"],
    "Reservationist": ["Customer Service", "Communication", "Problem Solving", "Attention to Detail", "Multitasking"],
    "Events Manager": ["Event Planning", "Project Management", "Communication", "Leadership", "Problem Solving"],
    "Meeting Planner": ["Event Planning", "Project Management", "Communication", "Attention to Detail", "Problem Solving"],
    "Lodging Manager": ["Hotel Management", "Leadership", "Customer Service", "Communication", "Problem Solving"],
    "Director of Maintenance": ["Maintenance Management", "Leadership", "Technical Skills", "Problem Solving", "Communication"],
    "Valet": ["Customer Service", "Communication", "Driving Skills", "Attention to Detail", "Physical Stamina"],
    "Doctor": ["Medical Knowledge", "Patient Care", "Communication", "Problem Solving", "Attention to Detail"],
    "Game Developer": ["Game Development", "Programming", "Creativity", "Problem Solving", "Teamwork"],
    "Marketing Executive": ["Marketing Strategy", "Communication", "Leadership", "SEO", "Social Media"],
    "Customer Service Executive": ["Customer Service", "Communication", "Problem Solving", "Leadership", "CRM"],
    "Digital Marketing Executive": ["Digital Marketing", "SEO", "Content Creation", "Social Media", "Analytics"],
    "Content Writer": ["Content Writing", "SEO", "Copywriting", "Editing", "Research"],
    "Sales Executive": ["Sales", "Communication", "Negotiation", "Customer Service", "CRM"],
    "Lawyer": ["Legal Knowledge", "Research", "Communication", "Negotiation", "Problem Solving"],
    "Merchant Navy": ["Navigation", "Safety", "Engineering", "Communication", "Teamwork"],
    "Chartered Accountant": ["Accounting", "Financial Reporting", "Taxation", "Auditing", "Compliance"],
    "Quality Assurance Tester": ["QA Testing", "Automation", "Attention to Detail", "Problem Solving", "Communication"],
    "AI Engineer": ["Machine Learning", "Python", "TensorFlow", "Data Analysis", "Algorithms"],
    "Machine Learning Engineer": ["Machine Learning", "Python", "Data Analysis", "Algorithms", "TensorFlow"],
    "Blockchain Developer": ["Blockchain", "Smart Contracts", "Cryptography", "Solidity", "Ethereum"],
    "Full Stack Software Developer": ["JavaScript", "React", "Node.js", "SQL", "HTML/CSS"],
    "Management Consultant": ["Consulting", "Business Strategy", "Data Analysis", "Communication", "Problem Solving"],
    "Engineering Manager": ["Leadership", "Project Management", "Engineering", "Communication", "Problem Solving"],
    "IT Systems Manager": ["IT Management", "Networking", "Security", "Project Management", "Leadership"],
    "Data Engineer": ["Data Engineering", "SQL", "Python", "ETL", "Big Data"],
    "Software Architect": ["Software Design", "Architecture", "Leadership", "Java", "Microservices"],
    "Investment Banker": ["Financial Analysis", "Investment Banking", "Excel", "Communication", "Negotiation"],
    "Surgeon": ["Surgery", "Medical Knowledge", "Attention to Detail", "Patient Care", "Communication"]
}

# Function to generate a random subset of skills for a given job title
def get_random_skills(job_title):
    skills = skills_dict[job_title]
    return random.sample(skills, k=random.randint(2, len(skills)))

# Generate the dataset in batches
def generate_job_listings_in_batches(num_records, batch_size):
    for _ in range(0, num_records, batch_size):
        job_listings = []
        for _ in range(batch_size):
            job_title = random.choice(job_titles)
            job_listings.append({
                'job_title': job_title,
                'skills': ', '.join(get_random_skills(job_title))
            })
        yield pd.DataFrame(job_listings)

# Generate and save a large number of synthetic job listings in batches
num_records = 1000000  # 1 million records
batch_size = 10000  # Batch size
for i, batch_df in enumerate(generate_job_listings_in_batches(num_records, batch_size)):
    if i == 0:
        batch_df.to_csv('synthetic_job_listings.csv', index=False, mode='w', header=True)
    else:
        batch_df.to_csv('synthetic_job_listings.csv', index=False, mode='a', header=False)

print("Dataset generation complete.")
